
@base = https://api.github.com 
@owner = facebook
@repo = react

GET {{base}}
Accept: application/vnd.github.v3+json




### Issues
GET {{base}}/repos/{{owner}}/{{repo}}/issues



### Repo
GET {{base}}/repos/{{owner}}/{{repo}}

### 
GET {{base}}/repos/{{owner}}/{{repo}}/commits

### pulls
GET {{base}}/repos/{{owner}}/{{repo}}/pulls


### contriubuers
GET {{base}}/repos/{{owner}}/{{repo}}/contributors


###commit count
GET {{base}}/repos/{{owner}}/{{repo}}/stats/participation

###Get the weekly commit count

GET {{base}}/repos/{{owner}}/{{repo}}/stats/code_frequency


### pulls
GET {{base}}/repos/{{owner}}/{{repo}}/pulls



